"""add new column

Revision ID: d266d71f9692
Revises: 
Create Date: 2026-01-27 01:44:09.301885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd266d71f9692'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_analyses_id', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_firebase_uid', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_incidents_detected_at', table_name='incidents')
    op.drop_index('ix_incidents_id', table_name='incidents')
    op.drop_index('ix_incidents_service_id', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_api_keys_id', table_name='api_keys')
    op.drop_index('ix_api_keys_is_active', table_name='api_keys')
    op.drop_index('ix_api_keys_key_value', table_name='api_keys')
    op.drop_index('ix_api_keys_project_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_health_checks_checked_at', table_name='health_checks')
    op.drop_index('ix_health_checks_id', table_name='health_checks')
    op.drop_index('ix_health_checks_service_id', table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index('ix_projects_guest_key', table_name='projects')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_is_active', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_services_id', table_name='services')
    op.drop_index('ix_services_is_active', table_name='services')
    op.drop_index('ix_services_name', table_name='services')
    op.drop_index('ix_services_project_id', table_name='services')
    op.drop_index('ix_services_service_state', table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('services_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('endpoint_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('http_method', postgresql.ENUM('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', name='httpmethod'), autoincrement=False, nullable=True),
    sa.Column('service_type', postgresql.ENUM('HTTP_API', 'HTTPS_API', 'GCP_ENDPOINT', 'FIREBASE', 'WEBSOCKET', 'GRPC', name='servicetype'), autoincrement=False, nullable=False),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('expected_status_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timeout_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failure_threshold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('service_state', postgresql.ENUM('HEALTHY', 'ERROR', 'INACTIVE', name='servicestate'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='services_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='services_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_services_service_state', 'services', ['service_state'], unique=False)
    op.create_index('ix_services_project_id', 'services', ['project_id'], unique=False)
    op.create_index('ix_services_name', 'services', ['name'], unique=False)
    op.create_index('ix_services_is_active', 'services', ['is_active'], unique=False)
    op.create_index('ix_services_id', 'services', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='projects_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_is_active', 'projects', ['is_active'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_index('ix_projects_guest_key', 'projects', ['guest_key'], unique=True)
    op.create_table('health_checks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('health_checks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_alive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('needs_analysis', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='health_checks_service_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_checks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_health_checks_service_id', 'health_checks', ['service_id'], unique=False)
    op.create_index('ix_health_checks_id', 'health_checks', ['id'], unique=False)
    op.create_index('ix_health_checks_checked_at', 'health_checks', ['checked_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('key_value', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='api_keys_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey')
    )
    op.create_index('ix_api_keys_project_id', 'api_keys', ['project_id'], unique=False)
    op.create_index('ix_api_keys_key_value', 'api_keys', ['key_value'], unique=True)
    op.create_index('ix_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('ix_api_keys_id', 'api_keys', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('incidents_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trigger_check_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'INVESTIGATING', 'RESOLVED', 'ACKNOWLEDGED', name='incidentstatus'), autoincrement=False, nullable=True),
    sa.Column('severity', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incidentseverity'), autoincrement=False, nullable=True),
    sa.Column('consecutive_failures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_affected_checks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ai_analysis_requested', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_analysis_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='incidents_service_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_check_id'], ['health_checks.id'], name='incidents_trigger_check_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incidents_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_service_id', 'incidents', ['service_id'], unique=False)
    op.create_index('ix_incidents_id', 'incidents', ['id'], unique=False)
    op.create_index('ix_incidents_detected_at', 'incidents', ['detected_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_firebase_uid', 'users', ['firebase_uid'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('root_cause_hypothesis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('debug_checklist', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('suggested_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('related_error_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('analysis_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='ai_analyses_incident_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_analyses_pkey'),
    sa.UniqueConstraint('incident_id', name='ai_analyses_incident_id_key')
    )
    op.create_index('ix_ai_analyses_id', 'ai_analyses', ['id'], unique=False)
    # ### end Alembic commands ###
